### ISSUE TITLE
Add funcionality for config editing

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/hugie#41]
It would be great to have some functionality to support the editing of the config JSONs.

**Comment by nsorros** [comment]
Is that similar to #8 ? Could you expand on the feature?

**Comment by ivyleavedtoadflax** [comment]
Yes similar to #8, but also we don't actually check anywhere that the config json is valid, so what i want it to do is:

1. Verify that the json is valid (being invalid was actually the cause of #40)
2. Allow what you describe in #8 so that you can just modify the config on the CLI without needing to edit a file manually. 
Some progress on this in https://github.com/MantisAI/hugie/pull/47

**Comment by nsorros** [comment]
This is exciting, keep going 👍
