### ISSUE TITLE
Handle 401 and 5xx errors in endpoint list

### ISSUE THREAD

**Issue by nsorros** [MantisAI/hugie#64]
The documentation for listing endpoints mentions a potential `401` error that we are not catching.

We are also not catching any 5xx erros which might occur if part of their API is down or not operational.

It would be good to add logic to handle those similar to what we do in the `create` command

**Comment by tarunsamanta2k20** [comment]
Where do I have to add it? i mean which file?

**Comment by nsorros** [comment]
> Where do I have to add it? i mean which file?

Hi @tarunsamanta2k20, it would be here https://github.com/MantisAI/hugie/blob/b4aea06bbe1f41a216781c12cceca2e545140534/hugie/endpoint.py#L32

Let us know if you have more questions
