### ISSUE TITLE
Add the variables from the config file as parameters with default values

### ISSUE THREAD

**Issue by nsorros** [MantisAI/hugie#74]
This will allow a user to run
```
hugie endpoint create --model-name tiiuae/falcon-40b --instance-type g5.12xlarge
```

and get and endpoint with an LLM relatively easily whereas with the config file, it is easy to mess something up.

**Comment by ivyleavedtoadflax** [comment]
Nice idea. My only question is how this can interact with the config, as I don't think we want to replace that functionality entirely.

Maybe we could have a flag to update the current config with the variables that we pass on the command line.

Perhaps also a command to output a config file based on the configuration of an existing endpoint. Not sure if this is possible. But fully recognise that many people will not care about the config at all, unless they have a production use case.

Also note #62. When thinking about this.
